name = "marked/luau_library_template"
version = "0.1.0"
description = "A Luau library template"
authors = ["marked"]
repository = "https://github.com/marked/luau-library-template"
license = "MIT"

[target]
environment = "luau"
lib = "lib/init.luau"

[engines]
lune = "^0.8.9"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
zune_std = { repo = "Scythe-Technology/zune-lib", rev = "d53309c08c94711aad48df5ca114bd3d0c3c8520" }
